-- ============================================
-- Database: RewardsDB
-- Service:  RewardsService (Port 5009)
-- Approach: Code First (EF Core Migrations)
-- Note:     This script is for reference only.
--           Database is created automatically
--           via EF Core migrations on startup.
-- ============================================

-- Table: RewardAccounts
-- --------------------------------------------
-- Id          INT           PK IDENTITY
-- AuthUserId  INT           UNIQUE NOT NULL (FK → AuthDB.Users.Id)
-- TotalPoints INT           NOT NULL DEFAULT 0
-- Tier        NVARCHAR(20)  NOT NULL DEFAULT 'Silver'
-- CreatedAt   DATETIME      NOT NULL DEFAULT GETDATE()

-- Table: RewardCatalog
-- --------------------------------------------
-- Id          INT           PK IDENTITY
-- Title       NVARCHAR(150) NOT NULL
-- Description NVARCHAR(300) NULL
-- PointsCost  INT           NOT NULL
-- Stock       INT           NOT NULL DEFAULT -1
-- IsActive    BIT           NOT NULL DEFAULT 1
-- CreatedAt   DATETIME      NOT NULL DEFAULT GETDATE()

-- Table: Redemptions
-- --------------------------------------------
-- Id              INT           PK IDENTITY
-- AuthUserId      INT           NOT NULL (FK → AuthDB.Users.Id)
-- RewardCatalogId INT           NOT NULL (FK → RewardCatalog.Id)
-- PointsSpent     INT           NOT NULL
-- RedeemedAt      DATETIME      NOT NULL DEFAULT GETDATE()

-- Seed Data: RewardCatalog
-- --------------------------------------------
-- Amazon Voucher Rs.100  → 100 points
-- Free Movie Ticket      → 500 points
-- Cashback Rs.50         → 200 points
-- Premium Membership     → 1000 points
