-- ============================================
-- Database: UserDB
-- Service:  UserService (Port 5005)
-- Approach: Code First (EF Core Migrations)
-- Note:     This script is for reference only.
--           Database is created automatically
--           via EF Core migrations on startup.
-- ============================================

-- Table: UserProfiles
-- --------------------------------------------
-- Id           INT           PK IDENTITY
-- AuthUserId   INT           UNIQUE NOT NULL (FK → AuthDB.Users.Id)
-- FullName     NVARCHAR(150) NOT NULL
-- DateOfBirth  DATE          NOT NULL
-- Address      NVARCHAR(300) NOT NULL
-- City         NVARCHAR(100) NOT NULL
-- State        NVARCHAR(100) NOT NULL
-- PinCode      NVARCHAR(10)  NOT NULL
-- CreatedAt    DATETIME      NOT NULL DEFAULT GETDATE()

-- Table: KycSubmissions
-- --------------------------------------------
-- Id              INT           PK IDENTITY
-- AuthUserId      INT           UNIQUE NOT NULL
-- DocumentType    NVARCHAR(50)  NOT NULL
-- DocumentNumber  NVARCHAR(50)  NOT NULL
-- Status          NVARCHAR(20)  NOT NULL DEFAULT 'Pending'
-- RejectionReason NVARCHAR(300) NULL
-- SubmittedAt     DATETIME      NOT NULL DEFAULT GETDATE()
-- ReviewedAt      DATETIME      NULL
